version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tuabi_db
      POSTGRES_USER: tuabi_user
      POSTGRES_PASSWORD: tuabi_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tuabi_user -d tuabi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./server
    environment:
      SERVICE: api
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      DATABASE_URL: postgresql://tuabi_user:tuabi_password@postgres:5432/tuabi_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 7d
      PAYSTACK_SECRET_KEY: sk_test_70c6c775e0169588132b6c504761debcf85a6a1d
      PAYSTACK_PUBLIC_KEY: pk_test_ed3746d376ed5f4e09fd8654cc7839e359a831ba
      FRONTEND_URL: http://localhost:3000
      AI_SERVICE_URL: http://ai-service:8000
    ports:
      - "3500:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    restart: unless-stopped

  ai-service:
    build: ./ai-service
    environment:
      DATABASE_URL: postgresql://tuabi_user:tuabi_password@postgres:5432/tuabi_db
      PORT: 8000
      LOG_LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./ai-service:/app
      - ai_models:/app/app/models/trained
    restart: unless-stopped

  worker:
    build: ./server
    environment:
      SERVICE: worker
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://tuabi_user:tuabi_password@postgres:5432/tuabi_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 7d
    depends_on:
      api:
        condition: service_started
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/uploads:/app/uploads
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  ai_models:
