version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tuabi_db
      POSTGRES_USER: tuabi_user
      POSTGRES_PASSWORD: tuabi_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass redis_password
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    environment:
      SERVICE: api
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 3000
      DATABASE_URL: postgresql://tuabi_user:tuabi_password@postgres:5432/tuabi_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 7d
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads

  worker:
    build: .
    environment:
      SERVICE: worker
      NODE_ENV: ${NODE_ENV:-development}
      DATABASE_URL: postgresql://tuabi_user:tuabi_password@postgres:5432/tuabi_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password
      JWT_SECRET: your-super-secret-jwt-key
      JWT_EXPIRES_IN: 7d
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
  redis_data:
