# fly.toml app configuration file generated for server-nameless-snow-6142 on 2025-07-31T08:50:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'server-nameless-snow-6142'
primary_region = 'lhr'

[build]

[env]
  PORT = "8000"
  NODE_ENV = "production"

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'ts-node prisma/seed.ts'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/health"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
